# Generated by Django 2.2.13 on 2020-08-04 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='관광지 태그 목록', to='tours.Tag', verbose_name='해시태그 목록'),
        ),
    ]
